### ISSUE TITLE
National Headline stats

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#105]
Add two headline figures: 
- 1. Last output from pv live, The latest black dashed value
- 2. Forecast value for the same time, the last solid yellow line

Already in UI:
- 3. The “Forecast next” value is the same as the current value we are displaying in the UI.

The times (10.30) in the descriptions are always the same as each other and change through the day. (Same as white line)

When a user moves the time (selected_time):
- 1. the PV live value at that time, if the time is in the future, just display the latest PV value. If both 'PV live initial' and 'updated' are present, select the 'updated' value
- 2. the OCF Forecast value at that time
- 3. Always the next OCF forecast value after 'now';

![Screenshot 2022-06-16 at 12 21 11](https://user-images.githubusercontent.com/34686298/174059428-a2f6ecf0-a96b-43fb-a855-5eced874b6aa.png)

**Comment by peterdudfield** [comment]
@dctanner would be great to have your design eye on this. 

This was request as part of a feedback session with NG - see other points https://github.com/openclimatefix/nowcasting/issues/102

**Comment by dctanner** [comment]
@peterdudfield I think it looks great. It's neat that we can have the text color match the chart and it's readable. 
Only note is for @dlinah and @Alaatohamy: the x padding for each number may need to reduce with slimmer window widths.

**Comment by peterdudfield** [comment]
Great thanks @dctanner 

I'll let @dlinah or @Alaatohamy decide who wants to take this on. Please do ask if there are any questions on this

**Comment by peterdudfield** [comment]
@dantravers can you check the description?
