### ISSUE TITLE
Add colour bar on map

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#106]
Add colour bar on map, so we know what yellow means. 
This would be great for both % and MW view

Something like this, but within the map
![Screenshot 2022-06-16 at 11 33 39](https://user-images.githubusercontent.com/34686298/174052005-2a6964dc-70d3-4968-ac9f-ca12a966a838.png)

**Comment by peterdudfield** [comment]
@dantravers

**Comment by Alaatohamy** [comment]
It does not exist in Mapbox as an option, but if you need it I can add the minimum and maximum values as text (not color bar)

**Comment by peterdudfield** [comment]
I think we need more than just the max and min values.How much effort would it be to add a colour bar? 
Perhaps we need to design it first if its not a standard thing

**Comment by dantravers** [comment]
Yes, I think if it's not a standard feature we should leave it out of scope for the June delivery.

**Comment by dantravers** [comment]
Pushing this back up priority now we have passed June and have feedback.
