### ISSUE TITLE
Int values

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#118]
<img width="676" alt="Screenshot 2022-06-20 at 10 02 12" src="https://user-images.githubusercontent.com/34686298/174566095-af8f8dbf-a6bf-4d11-a768-662841fd67a7.png">

I think all values are rounded to integers. Unfortunately Scotland GSPs look a bit odd

Is it correct this was done for speed? 
How much slower is this? 
Is there an option to not round the values for the charts?

**Comment by dantravers** [comment]
One possible way to do this would be to keep the headline figures the same, but for the chart line, plot the value (%_yield * max_installed_GSP_capacity)
So in the example in the screenshot, this would be 28%*3MW.  
The advantage of this is that the line chart would have 100 possible y values (so almost continuous values), while you don't need to change the headline.

**Comment by dlinah** [comment]
actually the first solution you suggested worked pretty well , thanks! @dantravers 

before 


![Image](https://user-images.githubusercontent.com/24292074/176014422-51ad8598-540c-4638-9bd4-332df0169ae9.png)


after


![Image](https://user-images.githubusercontent.com/24292074/176014467-3e5be97d-7354-4930-923f-96c0b1a9d5cf.png)

**Comment by dantravers** [comment]
Great- that looks great!
