### ISSUE TITLE
Add status banner

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting#122]
Add a status banner to the very top of the screen to show a warning message if returned by the API,

The API (https://api-dev.nowcasting.io/docs#/default/get_status_v0_GB_solar_status_get) returns a message: 
{
  "status": "string",
  "message": "string"
}
If the message string is non-empty, create a banner at the top of the screen as outlined, displaying the message.  The colour is 48B0DF.  Text is white.  Font size should be the same as the display of the MW and % next to the GSP region I.e. "77% 264MW / 342MW".  The rest of the screen should be moved down (let us know if this creates problems with the display).

if the Message string is empty, or status='ok', then show no banner at all
 
This is important as when the model has an issue, we want to be able to tell the users so they know which parts of the forecast they need to ignore, or that it is being worked on. 

![image](https://user-images.githubusercontent.com/38562875/174596029-658f5c2a-b8ea-4ad1-b4c6-dacfde4e718a.png)

**Comment by Alaatohamy** [comment]
@peterdudfield @dantravers is the message in the banner static or the one that comes from the API?
if it's static, what this time refers to?
