### ISSUE TITLE
remove the blue outline over the map on click region then chick left or right arrow

### ISSUE THREAD

**Issue by Alaatohamy** [openclimatefix/nowcasting#131]
@dlinah after merging [this PR ](https://github.com/openclimatefix/nowcasting/pull/123) this issue happens in development Branch

**Comment by peterdudfield** [comment]
This is now on development

**Comment by dlinah** [comment]
this is the default ui for any focusable element (ie: have tabindex), you can see it on main as well

**Comment by peterdudfield** [comment]
I think this can be closed @dlinah @Alaatohamy ?
