### ISSUE TITLE
Left-right hotkey allows you to go past the time range in the graph

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting#132]
You can go to the right into the future, past the time displayed in the line chart.  Can we limit it to be so that it stops at the left and right boundaries of the chart which is displayed?  

If this is hard, it isn't critical for July release, and we can tackle later.

**Comment by peterdudfield** [comment]
@Alaatohamy @dlinah @dctanner, would be great to briefly discuss this in todays meeting. 
Not a problem if you don't have time. 

This is the only one above Cypress testing

**Comment by peterdudfield** [comment]
Im just messing with this on app.nowcasting.io, and im now sure this is working yet. seem to still be able to go past the end.
