### ISSUE TITLE
Set y-axis scale on GSP line graphs to fixed rather than dynamic

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting#133]
**Current**
At the moment, the GSP y-axis scale is dynamic, so it is hard to tell at what yield or load factor they are generating at (you can look at the % number, but it isn't apparent at a glance).

**New feature**
Change is to make each GSP line graph y axis maximum be a fixed number per GSP.  This number is to be determined with a little analysis by the team.  It could be: 
1. the max of the GSP outturn values over the last year (maybe with a few % buffer to account for the last year not being the sunniest).  
2. fixed % of GSP installed capacities.  We could determine this % based on step one above.  This would be more robust against more installed capacity being installed in the GSP.  Expect this number to be a figure less than 100%. For example 90%

**Comment by JackKelly** [comment]
I'd go for the easier one to implement for now :slightly_smiling_face: 

Ultimately, we'd also want to update the "max Y axis per GSP" as and when GSPs get more PV installed. Which is happening fairly quickly at the moment!

**Comment by peterdudfield** [comment]
Solution was to round the ymax = installed capacity to the following levels
[3, 9, 20, 45, 60, 100, 200, 300, 450, 600]

**Comment by peterdudfield** [comment]
Ill close this issue, but leave the bug open
