### ISSUE TITLE
Default view of map shoudl be one level more zoomed in

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting#136]
Can we make it so that when you load the page, the map of the UK is one more level zoomed in, so there is not so much sea in the view.  Should look like this: 
![image](https://user-images.githubusercontent.com/38562875/176736019-2d2f7608-4fb9-4c49-8cb2-314510962813.png)

Low priority.

**Comment by peterdudfield** [comment]
This seems to change depending on your zoom level on your browser, and perhaps your screen size. 
I suggest we leave this for now, and see if any users come up with this same point
