### ISSUE TITLE
Status banner disappears for 5 seconds when you click away from window

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting#137]
The blue status banner (issue #122 ), disappears for 5 seconds if you go to another window, and then come back to the nowcasting window.  

This may seem trivial, but as the users in the control room are going to be in a hurry, there is a concern that they could miss warning messages as they won't look at the screen for long.  

Probably low-medium prioirty.

**Comment by Alaatohamy** [comment]
@dantravers sure I fixed it, @peterdudfield what is the interval I have to validate the status of the API?

**Comment by peterdudfield** [comment]
> @dantravers sure I fixed it, @peterdudfield what is the interval I have to validate the status of the API?

every 5 mins is fine, that'll be the same as the forecast refresh time right?
