### ISSUE TITLE
Make GSP max y-axis values to be more consistent 

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting#150]
In the line charts for the GSPs, the y-axis values are fixed (as requested in issue #133 ) per GSP.  The idea was that the fixed value should some percentage of installed capacity for the GSP (E.g. 90%).  I believe this may have been proxied by max outturn over the last year, which is OK also.  

At the moment however (to get around tick-mark issues), the max varies quite a lot between GSPs - see two images.  Both Landulph and Indian Queens are generating at 53% of installed capacity but appear very different on the graph.  This gives the wrong visual impression to the user, as it looks like Indian Queens is generating more.  
![image](https://user-images.githubusercontent.com/38562875/177807389-b809b976-e6d5-4284-bf60-8cdfc219a971.png)
![image](https://user-images.githubusercontent.com/38562875/177807460-1001dfd6-693e-43e6-b4ed-435c663ce44b.png)

**Comment by peterdudfield** [comment]
Should try adding 30 for 'BIRM_1'

**Comment by dantravers** [comment]
Great.  Can we add in 50 (or similar) and 70 (or 69 if multiple of 3 is better). 
And for teh small ones 6, 12, 15?
Thanks!

**Comment by peterdudfield** [comment]
6 works
12 works
15 doesnt work, but 16 does
50 doesnt work, nothing between 45 and 60 works
70 doesnt work, nothing between 60 and 80 works

**Comment by dantravers** [comment]
Thanks - if we were to use 70 or similar in that range - what is the issue generated - is it bad decimals, or like .5, which I think might be worht accepting if it fills this gap.

**Comment by peterdudfield** [comment]
<img width="1145" alt="Screenshot 2022-09-27 at 22 19 48" src="https://user-images.githubusercontent.com/34686298/192637684-f377c772-3d69-4e09-993f-2f8dde0ac6c7.png">

**Comment by dantravers** [comment]
Yes, agree - looks yuk.  
What about 72 - then the major tick marks would be 24, 48, 72.  It's not as round, but it's understandable and not too messy.  Maybe worth a look.  But if it's slowing you down, we can park this - it's low priority, but nice to tidy up!

**Comment by dantravers** [comment]
I get the problem now - that the graph tool fixes the major tick marks.  That is a pain!
