### ISSUE TITLE
Round map to levels

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#174]
Change the map opacity to 5  different levels. I think this can be done by rounding the results for the map.

Would be great to develop this, and then see this in action before merging. This is because infact we might need 6, or 4 different levels.

Suggest using
MW: 0, 100, 200, 300, 400, 500
% 0,  0.2, 0.4, 0.6 0.8, 1

**Comment by dlinah** [comment]
here's a preview for using these values to round
MW: 0, 100, 200, 300, 400, 500
% 0, 0.2, 0.4, 0.6 0.8, 1
<a href="https://www.loom.com/share/5ca0a54db34d4ce5bd5de4cef574ab59"><p>Solar PV Forecast - 10 August 2022 - Watch Video</p></a>
[![](https://cdn.loom.com/sessions/thumbnails/5ca0a54db34d4ce5bd5de4cef574ab59-with-play.gif)](https://www.loom.com/share/5ca0a54db34d4ce5bd5de4cef574ab59)

**Comment by dlinah** [comment]
% 0, 0.1, 0.2, 0.3 ...
<a href="https://www.loom.com/share/8299ac47d40c497bb750b00eadacbbbf"><p>Solar PV Forecast - 10 August 2022 - Watch Video</p></a>
[![](https://cdn.loom.com/sessions/thumbnails/8299ac47d40c497bb750b00eadacbbbf-with-play.gif)](https://www.loom.com/share/8299ac47d40c497bb750b00eadacbbbf)

**Comment by dantravers** [comment]
hi Lina - could we arrange a screenshare to look at this on wednesday?  It's hard to see easily on the video.

**Comment by dlinah** [comment]
yes sure , just sent you an invite

**Comment by peterdudfield** [comment]
@peterdudfield to review

**Comment by peterdudfield** [comment]
I like the 20%, next item is to add a key for gradient boxes (@dantravers )

**Comment by peterdudfield** [comment]
Need issue in #202 as we are happy with the rounding
