### ISSUE TITLE
External links not all working

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting#197]
In the bottom left of the app, the following links need to change.  Can we make: 
**Docs** point to https://openclimatefix.notion.site/openclimatefix/Nowcasting-Documentation-0d718915650e4f098470d695aa3494bf
**Help** sould either generate a mail automatically with the default mail application.  Or allow the user to copy the address to clipboard (I think the latter slightly better). 
Lastly - the Forecast Creation Time seems to have disappeared from the view completely.  I think that should be to the right of "Feedback".

**Comment by peterdudfield** [comment]
Thanks @dantravers for the link.

Help - should be able to add a 'copy' button into the text, that copies the email address. @dlinah you think this is possible?

Forecast creation time, is now under Data.

**Comment by dlinah** [comment]
@peterdudfield yes , we can add a copy on click

**Comment by peterdudfield** [comment]
this finished @dlinah i think its on development?
