### ISSUE TITLE
Update title text

### ISSUE THREAD

**Issue by braddf** [openclimatefix/nowcasting#223]
## Detailed Description
Changing National PV chart title from this:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/41056982/190608407-abcba7b6-c5b7-4780-ab68-d5a2efe374eb.png">

to this:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/41056982/190608489-32fb4c1c-a261-4d97-811f-7a7655ec4257.png">

**Comment by peterdudfield** [comment]
will do this with #216
