### ISSUE TITLE
Add latest API data to Map

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#23]
# Add the latest forecast to UK Map

<img width="531" alt="Screenshot 2022-05-09 at 09 55 05" src="https://user-images.githubusercontent.com/34686298/167375731-4e23bc61-3a4d-4d2e-b0ed-e00668ca1e9c.png">

- [x] The map should be zoomable

- hover over region should give PV value (needs designs)

API end point:
- v0/GB/solar/gsp/forecast/all
Note currently this takes a few seconds to load
This provider's 338 forecast (ignore the gsp_id=0)

```{
  "forecasts": [
    {
      "location": {
        "label": "string",
        "gspId": 0,
        "gspName": "string",
        "gspGroup": "string",
        "regionName": "string",
        "rmMode": true
      },
      "model": {
        "name": "string",
        "version": "string"
      },
      "forecastCreationTime": "2022-05-09T08:56:38.870Z",
      "forecastValues": [
        {
          "targetTime": "2022-05-09T08:56:38.871Z",
          "expectedPowerGenerationMegawatts": 0
        }
      ],
      "inputDataLastUpdated": {
        "gsp": "2022-05-09T08:56:38.871Z",
        "nwp": "2022-05-09T08:56:38.871Z",
        "pv": "2022-05-09T08:56:38.871Z",
        "satellite": "2022-05-09T08:56:38.871Z"
      }
    }
  ]
}
```
We should use the first `forecastValues` and use `expectedPowerGenerationMegawatts` for the value

## Colours: 
- yellow (hex in experiments folder)
- opacity, start at 0, going to 100%
- range 0 to 500 kw (would be good to be able to easily change the maximum, in the code)

## Refresh
- data should be refreshed every 5 mins. In the future, we can adjust the time the fresh is made

Make it vertical (northernly aligned), but have an easy way to change to a bearing of 90 (in the code)

## Future: 
Want to show animation / video of different forecasts, i.e 30 mins, 1 hour, 1.5 hours and 2 hours.

**Comment by flowirtz** [comment]
Just to add to that:

**1. Mock API Server**
I just remembered that I actually [already created a mock API server](https://github.com/openclimatefix/nowcasting/blob/d57138f58fa9e723b27ff5fd0e1fe138012fb596/apps/nowcasting-app/pages/api/forecasts/%5B...mockApiRoute%5D.ts)!
It's a bit old and probably outdated, so maybe [fetch new data from the dev API](https://api-dev.nowcasting.io/docs) and update accordingly.

**2. GSP Shape File**
https://github.com/openclimatefix/nowcasting/blob/5d0422e23bdfca9cd82b58ca63646ab64fd26fb1/apps/nowcasting-app/data/gsp-regions.json

**3. Plotting GeoJSON on Map using Mapbox**
You can [follow this great Mapbox tutorial](https://docs.mapbox.com/mapbox-gl-js/example/geojson-polygon/) to do that.
In addition, we already have implemented this as part of the ux-demos [here](https://github.com/openclimatefix/nowcasting/blob/5d0422e23bdfca9cd82b58ca63646ab64fd26fb1/apps/ux-demos/pages/vis2-map-poly.tsx). It's probably a bit more complicated to follow than the mapbox tutorial above though.

**Comment by peterdudfield** [comment]
@dctanner 
```
“hover over region should give PV value” - is this referring to the info box? If so, the design looks more like it should open on click (and the X button is used to close it)
```

**Comment by peterdudfield** [comment]
@dctanner  said:
```
 “We should use the first forecastValues ” - just to confirm, this means you will ensure the array in the API is always ordered (by date I assume?)
 ```

**Comment by peterdudfield** [comment]
> @dctanner
> 
> ```
> “hover over region should give PV value” - is this referring to the info box? If so, the design looks more like it should open on click (and the X button is used to close it)
> ```

I was thinking,of a quick hover to show the forecast value, and the 'info box' is the click event that is in #27 that shows much more detail

**Comment by peterdudfield** [comment]
> @dctanner said:
> 
> ```
>  “We should use the first forecastValues ” - just to confirm, this means you will ensure the array in the API is always ordered (by date I assume?)
> ```

Yea that does assume they are ordered, let's assume they are orderd in time, and then use the first one. Would be good if this was very easy to change (in the code) so that we might want to display the 3rd value instead

**Comment by peterdudfield** [comment]
> > @dctanner
> > ```
> > “hover over region should give PV value” - is this referring to the info box? If so, the design looks more like it should open on click (and the X button is used to close it)
> > ```
> 
> I was thinking,of a quick hover to show the forecast value, and the 'info box' is the click event that is in #27 that shows much more detail

I'm happy to split this out to a separate issue if you like @dctanner

**Comment by dctanner** [comment]
> > > @dctanner
> > > ```
> > > “hover over region should give PV value” - is this referring to the info box? If so, the design looks more like it should open on click (and the X button is used to close it)
> > > ```
> > 
> > 
> > I was thinking,of a quick hover to show the forecast value, and the 'info box' is the click event that is in #27 that shows much more detail
> 
> I'm happy to split this out to a separate issue if you like @dctanner

That might be best. We also need a quick design for it. Also when showing expectedPowerGenerationMegawatts values should 'MW' be appended?

**Comment by peterdudfield** [comment]
> @peterdudfield if the yellow shading is showing an absolute Mw between 0 and 500, should we have a key somewhere so which shades of yellow equals what MW amount. If there is no key, should we show the expectedPowerGenerationMegawatts in the pop up, as well as the Percent of total?

Sorry this is all a bit of working progress, 


1. Lets try without a key first, and we can always add it if we need it. That ok?
2. Yea, I think that is a good idea, by the end of the week we should know what will be in that pop up

**Comment by dctanner** [comment]
> * range 0 to 500 kw (would be good to be able to easily change the maximum, in the code)

Btw did you mean MW here, as this is what expectedPowerGenerationMegawatts is in.

**Comment by peterdudfield** [comment]
> > * range 0 to 500 kw (would be good to be able to easily change the maximum, in the code)
> 
> Btw did you mean MW here, as this is what expectedPowerGenerationMegawatts is in.

Yea sorry my mistake, yea [MW]
