### ISSUE TITLE
Display when the forecast was created (0.1)

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#24]
Show OCF Forecast Creation Time on bottom of left side:

![image](https://user-images.githubusercontent.com/227/168838905-1a15f766-efcf-40a2-9cb3-0de55282c160.png)

This information can be retrieved from

[/v0/GB/solar/gsp/forecast/all](http://nowcasting-api-development.eu-west-1.elasticbeanstalk.com/docs#/default/get_all_available_forecasts_v0_GB_solar_gsp_forecast_all_get)

and see `forecast_creation_time`

**Comment by dctanner** [comment]
Covered in #26

**Comment by peterdudfield** [comment]
Hey @dctanner 

Yea two different times, 
- target time: in the top left
- creation time: could that go on the bottom? Nudge me on slack if you want a call

**Comment by peterdudfield** [comment]
Actually i put this as a bug on myside

**Comment by peterdudfield** [comment]
I'm not sure the bug is on myside

When I query the api I see the forecast creation time to be within the last 5 mins (approx)

![Uploading Screenshot 2022-06-14 at 19.17.59.png…]()
<img width="378" alt="Screenshot 2022-06-14 at 19 18 44" src="https://user-images.githubusercontent.com/34686298/173661022-15d88e7f-bb78-41fd-95da-e2b9a8c707a7.png">

However on the front end, the forecast is made 2 weeks ago. I'm not quite sure how this happened? 
https://github.com/openclimatefix/nowcasting/blob/main/apps/nowcasting-app/components/map/pvLatest.tsx#L29
