### ISSUE TITLE
Add 0-50 bucket in chart key

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#244]
Add 0-50 bucket in chart key
Also add 0-10% for '%' view

![Screenshot 2022-09-27 at 11 32 10](https://user-images.githubusercontent.com/34686298/192503208-3291db78-a2df-427d-b55e-893436c81ae0.png)

@dantravers : Will need help  of design as text will not show up on 'no-color' background

**Comment by braddf** [comment]
Included in issue #258 and in PR #262 👍
