### ISSUE TITLE
Add a staging env

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#25]
Add staging enviornment, perhaps from development branch

Then we can use a `gitflow` framework

**Comment by flowirtz** [comment]
The `staging` branch is now deployed on https://staging-app.nowcasting.io/

There is still some issue with Auth0, didn't investigate yet.

**Comment by peterdudfield** [comment]
Ive moved this to 'development' branch and https://development-app.nowcasting.io/, to be slightly more inline wiht gitflow workflow

**Comment by peterdudfield** [comment]
@all-contributors please add @flowirtz for code

**Comment by peterdudfield** [comment]
@all-contributors please add @dantravers  for ideas
