### ISSUE TITLE
[meta] Designer issue list from 29/09/22

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/nowcasting#255]
#### Tasks 

- [x] #256 
- [x] #257
- [x] #258
- [x] #265 
- [x] #266 

#### Tasks that may need more discussion
- [x] #175 
- [x] #261 
- [x] #254  
- [x] #260 

## Context

These are the issues from our first meeting with Elisabeth Mayr, the new designer. The design prototypes and team comments for these issues can be found [here](https://www.figma.com/file/5RmuNt9H2398bXDGmPoz6V/Developer-Handoff?node-id=0%3A1). 

## Possible Implementation

Please see individual issues descriptions.

**Comment by peterdudfield** [comment]
Thanks @rachel-labri-tipton for putting this together
