### ISSUE TITLE
Change national forecast header 

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/nowcasting#256]
## Detailed Description

The National Forecast header should be updated (see images below).  

Here is the [Figma design prototype](https://www.figma.com/file/5RmuNt9H2398bXDGmPoz6V/Developer-Handoff) that relates to this issue. 

Current national forecast header: 

![Screenshot 2022-09-29 at 12 04 54](https://user-images.githubusercontent.com/86949265/193003437-a175ca1f-4beb-4661-a8a0-e797bd8a808f.png)

Suggestion for update: 
<img width="549" alt="Screenshot 2022-10-06 at 23 13 12" src="https://user-images.githubusercontent.com/86949265/194419646-c3bb1620-7865-4251-8227-ac0dca5b3fec.png">

## Context
These changes are part of an iterative process to update the pv-remix charts area of the Nowcasting App to 

## Possible Implementation
You might want to start by looking in the `forecast-header` folder in `components`.

**Comment by peterdudfield** [comment]
Yea we should keep PVlive updated and estimate on the tooltip
