### ISSUE TITLE
Create a slider for the chart to slide across the map

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/nowcasting#260]
## Detailed Description

Create a slider resize the pv remix chart window, replacing the expand and contract arrows that current expand and contract the charts. While maybe a bit tricky to implement, this will make the page a bit cleaner. 

Current: 

![Screenshot 2022-09-30 at 10 41 50](https://user-images.githubusercontent.com/86949265/193230127-a83c31f7-9a78-43eb-acc0-d370e9fda120.png)

![Screenshot 2022-09-30 at 10 41 27](https://user-images.githubusercontent.com/86949265/193230033-ab7b8f25-a0e1-4e7e-afe7-98e082797ef7.png)

Suggestion: 

View the relevant prototype [here](https://www.figma.com/file/5RmuNt9H2398bXDGmPoz6V/Developer-Handoff?node-id=0%3A1). 

## Context

This will make the page a bit sleeker. 

## Possible Implementation
Remove resize arrows and implement slider. Probably easier said than done.

**Comment by peterdudfield** [comment]
Close this for now, as we no
