### ISSUE TITLE
Click GSP on map to show GSP chart on left (3)

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#27]
As an extension from https://github.com/openclimatefix/nowcasting/issues/26, we want to allow users to click a GSP region on the map, and show the OCF Forecast and PV Live chart for the selected GSP on the left.

![image](https://user-images.githubusercontent.com/227/168843950-fd9b94c7-481e-4c63-941a-b8805e75a189.png)

- Click on any GSP region on the to map to select it
- Show 4px #ffffff border around selected 

Use same API calls as for National, but using {gsp_id} of selected GSP region.

On left side, below National chart, show:

- Title of GSP region (shown as "Peterborough" in design)
- forecasts[30minNOW].expectedPowerGenerationNormalized as percentage (shown as "56%" in design)
- Part shown as "217 / 541 MW" in designs is "{forecasts[30minNOW].expectedPowerGenerationMegawatts} / {location.installedCapacityMw} MW". Use /v0/GB/solar/gsp/gsp_systems to get the installedCapacityMw values.
- Close button which de-selects the GSP in the map, removes all the GSP info from the left side and goes back to the regular National view.
- GSP chat which works exactly the same as the National chart, but for the selected {gsp_id} data from the API.

Note:

- The 'white now line and label' in the charts should be linked, so in future you will be able to click on either the National or GSP chart, and move the white now line, and it will update on both charts.
- When you click a GSP on the map, we need to do several API calls to get the data for this GSP's chart. We should show a loading spinner in the left hand space where the GSP chart will go whilst it loads.

```<svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
      </svg>```

**Comment by dctanner** [comment]
> % of power is calculated by taking the power value and dividing by the installed capacity of the GSP.

Is this meant to be different to the way the gsp yellow opacity is calculated (divided by 500 MW)?

**Comment by dctanner** [comment]
> * % of power is calculated by taking the power value and dividing by the installed capacity of the GSP

@peterdudfield Is this meant to be different to the way the gsp yellow opacity is calculated (divided by 500 MW)? If so, should we also display the expectedPowerGenerationMegawatts in this popup, so it's a bit more clear that the % value is different from the way the opacity is calculated?

**Comment by peterdudfield** [comment]
Yea, each gsp will have a different capacity, so it maybe at 100%, but only be producing 50 MW of power. 
Yes, I think both values should be displayed

**Comment by peterdudfield** [comment]
@dctanner would be great for you review on this

**Comment by dlinah** [comment]
@peterdudfield  i'm using `/GB/solar/gsp/forecast/latest/${gspId}` to get the `expectedPowerGenerationNormalized` (using the apis for national with diffrent `gspId` like you mentioned ) but i'm  getting `expectedPowerGenerationNormalized= null`?

**Comment by peterdudfield** [comment]
Please see documentation [here](http://nowcasting-api-development.eu-west-1.elasticbeanstalk.com/docs#/default/get_all_available_forecasts_v0_GB_solar_gsp_forecast_all_get)

You need to add 'normalize=true'

**Comment by dlinah** [comment]
@peterdudfield so we are not gonna use `/GB/solar/gsp/forecast/latest/${gspId}` (which does not have normalize param), ok

**Comment by peterdudfield** [comment]
> @peterdudfield so we are not gonna use `/GB/solar/gsp/forecast/latest/${gspId}` (which does not have normalize param), ok

What are trying to get? You dont need to normalize anything for the 'GSP' plot

**Comment by peterdudfield** [comment]
Note: this call http://nowcasting-api-development.eu-west-1.elasticbeanstalk.com/docs#/default/get_systems_v0_GB_solar_gsp_gsp_systems_get will give you the GSP details
