### ISSUE TITLE
[meta]  delta view initial iteration

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/nowcasting#287]
The following tasks initiate the `delta view` that will be added to the `nowcasting app` showing how much PV is produced over or under the OCF forecast. The design in progress can be found [here](https://www.figma.com/file/5RmuNt9H2398bXDGmPoz6V/Developer-Handoff?node-id=1%3A2804). None of these designs are yet completed, but the idea with this meta issue is to get started with an initial plotting of the data to figure out what designs are possible. 

The Delta View will look something like this: 
![Screenshot 2022-11-10 at 11 02 01](https://user-images.githubusercontent.com/86949265/201061037-65903ab9-85c4-455d-9c3d-0044df21ed51.png)

#### Page Setup
- #293 

#### Quick plot of delta view 

- #296
- #297 

#### Independent page components
- develop utilities you need to import data into page components
- #294
- #295
- #298 
- #299 
- Refine delta national with comments

### Phase II Tasks
- Get data to work for `GSP delta chart`
- show historic data

### Possible Implementation
See issue details.

**Comment by peterdudfield** [comment]
I think we can close this for now
