### ISSUE TITLE
Various small fixes, doc link, rounding, % style, + time

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting#290]
- Documentation link isn't working - but known issue to be fixed
- Rounding bug has crept back in (where the numbers are truncated to integers in the GSP line graphs.  You notice it for the GSPs with small capacities - e.g. London)
- make the % in the GSP header a bit tighter to the right
- Add a little padding to the "%" button in the map view
- Add the time into the Date on the map.  E.g. Monday 7th November 2022, 14:00

**Comment by rachel-labri-tipton** [comment]
hi @dantravers, For the task "Add a little padding to the `%` button in the map view", do you mean just making sure there's more space between the `capacity` button and the `%` button? thanks!

**Comment by dantravers** [comment]
I just mean making the % button a bit wider.  At the moment it's very narrow, so make it as wide as the MW button at least. I think Brad may have done this in the branch he created.

**Comment by rachel-labri-tipton** [comment]
Yeah, that one is fixed already.
