### ISSUE TITLE
delta - design national delta view chart and get data to plot delta values 

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/nowcasting#296]
Please see https://github.com/openclimatefix/nowcasting/issues/287 for meta delta view feature description. Designs are [here](https://www.figma.com/file/5RmuNt9H2398bXDGmPoz6V/Developer-Handoff?node-id=1%3A2804).
Work done on the feature should be done on a feature branch off of the `delta-view` branch.

### Detailed Description
Below the header, much like the PVForecast view, the delta page will have a chart showing the delta, which is the difference between the last forecast value and the actual value. 

- design the national delta view chart (see below). it'll have a bit different y-axis than the `national pv remix chart`
- plot the PV actual values
- plot the delta values 
- maybe think about whether or not we 

![Screenshot 2022-11-10 at 15 58 13](https://user-images.githubusercontent.com/86949265/201125860-1d429865-5268-4fcf-b429-2ab05a9d9c36.png)

As you may notice, there are some bars on here indicating over and under the projected values. 

### Possible Implementation
Look at the code for the national `PV remix chart` as a template.

**Comment by peterdudfield** [comment]
Some comments on vercel
