### ISSUE TITLE
Add map toggle controls: PV FORECAST, SOLAR SITES, DELTA

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#30]
Add toggle for
- PV forecasts
- PV sites (set button state to disabled to cursor changes when hovering over it)
- Delta (set button state to disabled to cursor changes when hovering over it)
- 
<img width="151" alt="Screenshot 2022-05-09 at 11 00 16" src="https://user-images.githubusercontent.com/34686298/167387518-1783f211-5c27-44ac-b425-c98dc6d956d2.png">

**Comment by dctanner** [comment]
Just to confirm, the toggle doesn't do anything at this adage and is just visual.

**Comment by peterdudfield** [comment]
> Just to confirm, the toggle doesn't do anything at this adage and is just visual.

correct - thanks

**Comment by dctanner** [comment]
They should be positioned in the top left of the map
<img width="953" alt="CleanShot 2022-05-16 at 11 34 20@2x" src="https://user-images.githubusercontent.com/227/168777747-5083be73-0c79-47ed-8e69-73a51d8374cb.png">
.
