### ISSUE TITLE
Having to re-login to Development site regularly

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting#302]
Since the Auth0 changes to dev, I've had to login a couple of times to get the data.  It doesn't log me out, but I get no data, so I have to log out and in again to get it working.  

Doesn't seem to happen every day, but definitely happened Friday and today (Tuesday), since I first re-logged in after Auth0 changes.

**Comment by peterdudfield** [comment]
I get this too, loging in and out sorts it, but i suspect it happens every day. I think this is a critical bug that we should fix before release

**Comment by dantravers** [comment]
Just checked, and confirm it happened 2 days in a row - probably does every day.  And agree that it should be P1.

**Comment by peterdudfield** [comment]
This has happend to me recently, @dantravers still happening to you?

**Comment by dantravers** [comment]
hi - yep, just happened now.  I re-logged in 2 days ago.  I checked yesterday and it was fine.  But today it's thrown me out again.

**Comment by peterdudfield** [comment]
Ok it did just happen to me again

**Comment by peterdudfield** [comment]
@braddf did you say you deployed a fix to this on Mondy?

**Comment by braddf** [comment]
I did, so just need confirmation that this is no longer happening on `staging` ideally

cc @dantravers

**Comment by peterdudfield** [comment]
> I had a thing where I had the errors but it said it was deploying a vercel preview, so I'm not sure if it was being masked or not.

do you know what time that was? @braddf might have done a deployment onto staging then

**Comment by dantravers** [comment]
> > I had a thing where I had the errors but it said it was deploying a vercel preview, so I'm not sure if it was being masked or not.
> 
> do you know what time that was? @braddf might have done a deployment onto staging then

~4pm wednesday 23rd.

**Comment by peterdudfield** [comment]
I think it just happened to me, think we need to reduce the timeout to say 10 mins, and test properly

**Comment by peterdudfield** [comment]
Dan also had this sunday night

**Comment by peterdudfield** [comment]
@braddf and I, just reduced the token to 60 seconds and we could see the refresh token working. Bit unsure what whats happenening, and therefore would like to leave it a few more days. 
If it does happen again, lets write here with a proper timestamps so we can investigate further if needed be

**Comment by dantravers** [comment]
I found the error came back for me on staging.nowcasting.io.  I opened the app this morning.  I think I last logged in Monday this week (today is Thursday) or maybe the end of last week.

**Comment by peterdudfield** [comment]
Now it goes to - logged out page - https://staging.nowcasting.io/logout. This happen after having the web page open for > 1 day

**Comment by peterdudfield** [comment]
now on production

**Comment by dantravers** [comment]
Seen it, logged in, clicked around.  

 

Looks great!

**Comment by peterdudfield** [comment]
Close this for the moment, un less it comes up again
