### ISSUE TITLE
Should we show 2 days of history

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#303]
## Detailed Description
Currently we show today and yesterday. Should we show a full 2 days of history. This has the advantage of always having the solid black line on it. Currently between 00:00 and 10:45 ish there is no solid black line

![Screenshot 2022-11-18 at 10 40 43](https://user-images.githubusercontent.com/34686298/202685686-b86c2694-133b-4a8f-ae82-e03e9fb71410.png)

## Possible Implementation
- 2 lines of code need chaningin in the API
- possibily we should add a date to the x axis on the plots

**Comment by peterdudfield** [comment]
@dantravers @braddf and @rachel-labri-tipton would be interested in your thoughts

**Comment by dantravers** [comment]
I think I'd say we should wait until we have the overall consideration of the x-axis views in the UI.  We have the day ahead hopefully coming soon and then we'll need to have some way of selecting days.  I'm also conscious that Alex is keen to just get it out there. 

Having said that, if it is a very easy change, we could put it in a Vercel branch and trial it for a while?

**Comment by peterdudfield** [comment]
Ill close this for the moment
