### ISSUE TITLE
Change tooltip order (in Staging, ready for production)

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting#309]
This was part of another issue, but I think it got lost somewhere as there were a number of small fixes in there. 

Can we change the order of the tooltip over the line graph to be: (OCF Forecast, PV Live updated, PV Live initial estimate), when we have all three present?

(Currently the last two are swapped, but the main 2 numbers to compare are OCF Forecast & PV Live Updated, so it would be easier for the user to read in this order).

**Comment by rachel-labri-tipton** [comment]
hey @dantravers, I'm just going through and cleaning up and closing nowcasting github issues that have been addressed. 
this was an issue you flagged in late november. 
I think we've sorted the tooltip for the PV Forecast charts. if not, feel free to leave a vercel comment on the `delta view` or `staging` deployed branches.

**Comment by dantravers** [comment]
Agree.
