### ISSUE TITLE
sentry-related API request failed error 

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/nowcasting#317]
**Describe the bug**
When pushing to both the `delta-view` branch and `staging` last week, I got an API request failed error: 
[https://vercel.com/openclimatefix/nowcasting-app/CAr6SEZ9RtpQZP1cTxD5a4jxcaVo](https://vercel.com/openclimatefix/nowcasting-app/CAr6SEZ9RtpQZP1cTxD5a4jxcaVo)

It looked something like this: 

<img width="1230" alt="Screenshot 2023-01-23 at 10 11 42" src="https://user-images.githubusercontent.com/86949265/214002606-dc9f826f-e72c-499f-830c-7158b3ad7e57.png">

Here's the link to the build error from `staging`: 
[https://vercel.com/openclimatefix/nowcasting-app/ECbptRyjicboP5yuksrbr8hs66Az
](https://vercel.com/openclimatefix/nowcasting-app/ECbptRyjicboP5yuksrbr8hs66Az)
@peterdudfield suggested waiting until @braddf was back from vacation to have a look at it.

**Comment by peterdudfield** [comment]
I think this is now fixed
