### ISSUE TITLE
future 4 hour delta view

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#320]
Need a way to get all GSP 4 hour view for the future. This is so on the delta page the map cab be displayed

# Detailed Description
Need to add in a method in [v0/solar/GB/gsp/forecast/all/](/v0/solar/GB/gsp/forecast/all/)

Would like to add `forecast_horizon_minutes` into this method. This can set to 240 to get the 4 hour view

# Context
- Current there is only a method for one GSP view - [national](/v0/solar/GB/national/forecast) and [gsp](/v0/solar/GB/gsp/forecast/{gsp_id})
- There are quite a few different sql tables, for different reasons
- `Forecast` - this holds metadata of the forecast, and is linked to `ForecastValues` tables
- `ForecastVaue`, actual forecast values for one `target_time`. A list of this are connected to a `Forecast` item
- `ForecastValueLatest` - this saves the last forecast value for each target time
- `ForecastValueSevenDaysSQL` - this contains the Forecast Value for the last seven, this makes it easier to load
- We currently only use `ForecastValueSevenDaysSQL` for loading 4 hour view for one specific `gsp id`

# Possible Implementation
Few general options
1. Create a 4 hour table. 
    - Pro: This would speed up loading the 4 hour view, 
    - Con: Then stuck on 4 hour view. Can easier swicth to 1 hour view
    - Days of work: 5
2. Clean database - only save 3 days of data. 
    - Pro: Lots of speed issues would go away,
    - Con: doesnt then scale for history view
    - days of work 3
3. Caching layers on top of database. 
    - Pro: This would speed up all querys. 
    - Con: The cache would have to displayer after 5mins, so it might not be that useful. 
    - Con: Need new infrastrcutre
    - Days of work 20 +- 10 (bit un knowned)
4. Load 4 hour view from  `ForecastValueSevenDaysSQL` table
    - Pro: Only need to update read function
    - Con: Dont know how fast this function will be 
    - Days of work 2: 

## 4. Load from `ForecastValueSevenDaysSQL` table

API. Add two new variables to [v0/solar/GB/gsp/forecast/all/](/v0/solar/GB/gsp/forecast/all/)
- forecast_horizon_minutes
- only_forecast_values

If `only_forecast_values` is not `None` then should use [`get_forecast_values`](https://github.com/openclimatefix/nowcasting_datamodel/blob/main/nowcasting_datamodel/read/read.py#L374) read function. This change is done in [src/database.py](https://github.com/openclimatefix/nowcasting_api/blob/main/src/database.py#L48) and goes in the 
 none `historic` bit of this function

Question for @braddf do you only need this values in the future, not in the past? for the `delta view`

Data model: 
- Adapt `get_forecast_values` read function to take several `gsp_ids`. Need to put this variable in the distinct and use `is_in` function

**Comment by braddf** [comment]
Re future values for `delta view` - yep, we only need now and forward, no historic, hopefully that makes it easier too..? 😅 🤞

**Comment by dantravers** [comment]
Question on (4): Would this solution allow another user to have a different number of hours (E.g. a 12 hour forecast)?
And also on (4): Is there a significant risk the new query will be too slow?  Or how slow do you think worse case is?

**Comment by peterdudfield** [comment]
4a yes we could do 12 hours
4b, there is a risk, but we are loading from a table which only has 7 days of data in it, so it should be fairly fast. But really we have to try it, and see. My feeling is it should be fun

**Comment by dantravers** [comment]
Thanks.  For: 
> 4a yes we could do 12 hours
Is any number of hours just as possible if requested E.g. 6 or 24, etc..?

**Comment by peterdudfield** [comment]
> Thanks. For:
> 
> > 4a yes we could do 12 hours
> > Is any number of hours just as possible if requested E.g. 6 or 24, etc..?

any number is possible

**Comment by peterdudfield** [comment]
I moved the API specifc task into here - https://github.com/openclimatefix/nowcasting_api/issues/175
