### ISSUE TITLE
[meta] issue PVSite / Solar Sites UI 

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/nowcasting#323]
### Meta mvp task list for the PVSite (Solar Sites) UI 

This feature is the UI that will be built for nowcasting users with specific solar sites for which OCF will be generating a forecast. This feature will be integrated into the current `nowcasting app`. 

We will be completing most of these tasks on a single branch and this will be the `mvp` for the `solar sites`. 

These tasks were drafted based on the following design: 
[Here's the design in Figma.](https://www.figma.com/file/5RmuNt9H2398bXDGmPoz6V/Developer-Handoff?node-id=642%3A48544&t=jnKqOBRs4ehXGWPH-0)

Here's the design as a screenshot: 

<img width="928" alt="Screenshot 2023-02-08 at 11 54 41" src="https://user-images.githubusercontent.com/86949265/217510049-6f4f9881-82d2-4d8c-860d-60b46c55928d.png">

### Phase I

- [x] #325
- [x] #324

#### Table 
- [x] #326
- [x] #327

#### Map 
- [x] #329
- [x] #330
- [x] #331
- [x] #332
- [x] #333
- [x] #334
- [x] #343 

#### Data 
- [x] #335
- [x] #336

Please view the separate issues for more details.

**Comment by peterdudfield** [comment]
amazing!!!!
