### ISSUE TITLE
Staging: Map funny distirbution

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#351]
On staging, the distirbution of gsp filled in colours seems wrong

![Screenshot 2023-04-12 at 10 53 25](https://user-images.githubusercontent.com/34686298/231423074-cbfa276b-b83e-4856-8b54-8bff5ecedf7d.png)

production

![Screenshot 2023-04-12 at 10 54 43](https://user-images.githubusercontent.com/34686298/231423163-21e2a040-2959-449a-9272-925448356e6b.png)

**Comment by peterdudfield** [comment]
When I deployed national on production this also happened

**Comment by peterdudfield** [comment]
I think its something to do with `forecast/all` so trying to remove national from this using - https://github.com/openclimatefix/nowcasting_api/pull/208

**Comment by peterdudfield** [comment]
I think I found it, `forecast/all` returns nationals, so want to remove that in the API. Need to adjust code [here](https://github.com/openclimatefix/nowcasting_datamodel/blob/main/nowcasting_datamodel/read/read.py#L249)

Then need to remove the code int he front end where `slice(1)` is used to remove national. 

This solution will be more robust

**Comment by braddf** [comment]
@peterdudfield - have updated/applied API to latest version (1.3.10) on `development` amended the FE code here to reflect the change (removed the slice and checked GSPs match now) and seems to be working on Staging 👍
