### ISSUE TITLE
Tooltip isn't displaying some future values

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting#357]
The tooltip (PV Forecast & Delta views) doesn't seem to show values past about 2 hours into the future.  Just shows dashes.  See screenshot. 
![image](https://user-images.githubusercontent.com/38562875/235646409-41d19e99-387a-46e4-8ede-1c84e575aaf7.png)

**Comment by peterdudfield** [comment]
<img width="368" alt="Screenshot 2023-05-10 at 14 43 56" src="https://github.com/openclimatefix/nowcasting/assets/34686298/1cb8fbcc-b601-439c-b8d6-0ff8d05a2226">

Looks like after 4 hours its not on there, this is only on development

**Comment by peterdudfield** [comment]
@braddf this might be for you to have a look at
