### ISSUE TITLE
Chart brush feature (2)

### ISSUE THREAD

**Issue by dctanner** [openclimatefix/nowcasting#37]
So that we can choose the chart period to view and 'brush' into the past, we will add a mini-chart below the main one, and enable the Recharts brush feature.

Here's an example: https://codesandbox.io/s/synchronized-line-charts-forked-nlkgkd?file=/src/App.tsx

The brush mini-chart should be at the bottom of the left side. Here's how it would look:
![image](https://user-images.githubusercontent.com/227/168841871-6d8e0a16-4465-4a34-bd64-daad5fca8ae3.png)

When you change the zoom level, both the National and GSP charts update at the same time.

We need to decide what the default zoom level is. To start with, we could just make the default zoom level to be all of the history (so the left and right brush handles are all the way to the left of the right, and all the data is in view).
The "Reset Zoom" button should be hidden by default when you load the app. When you interact with the brush mini-chart the "Reset Zoom" button should appear. When you click it, it resets to the default zoom level (mentioned above), and then the "Reset Zoom" button disappears again.

**Comment by dantravers** [comment]
Looks good. I would set default zoom as yesterday and today. 
We need to introduce date in there somehow - just having it on the top right isn't enough.  Suggest it is either in the very bottom one (which shows date only).  Or we show it in the x-axis of the zoomed chart - just once / day though.
