### ISSUE TITLE
Some Scottish GSPs appear wrong

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting#370]
The GSP highlighted (and some of the other ones in Scotland especially), appear to be forecasting too high.  They are showing 90+% yield.  
In production. 
![image](https://github.com/openclimatefix/nowcasting/assets/38562875/e7cc0968-5391-44dc-ad0d-32c767e74a15)

**Comment by peterdudfield** [comment]
Thanks @dantravers  (good bug report), 

In the database the MW installed capacity is 1.88 MW. 

So 1.4/1.88 = 74%, so I agree it should be in the 70-90 range. Let me ping the api

**Comment by dantravers** [comment]
thanks @peterdudfield.  Even in 70-90% range, it feels odd though.  There are a few Scotish GSPs with large outturns, and cloud cover, while not 100%, isn't at all clear-sky conitions.  That could be a more detailed aspect of the forecast in such GSPs. 
![image](https://github.com/openclimatefix/nowcasting/assets/38562875/95d5856d-0693-4fc4-9f3e-1869df856068)

**Comment by dantravers** [comment]
Looking at this further - maybe it's also to do with PV_Live.  The intra-day estimate is 1.9, whcih is higher than the reported capacity of 1.88!?
![image](https://github.com/openclimatefix/nowcasting/assets/38562875/d6d83633-e8e0-4307-9313-b761d20efb6e)

**Comment by peterdudfield** [comment]
Ah, I found something that the capacity is 1MW not 1.88MW when looking at `https://api.quartz.solar/v0/system/GB/gsp/?gsp_id=130`

Lets check another one, `Norwich Main`, currently at 10-30%. 47.2 MW and capacity is 336, so 47/336 = 0.13%

**Comment by peterdudfield** [comment]
My guess 1.9 is a rounding up of 1.88,  `https://api.quartz.solar/v0/solar/GB/gsp/pvlive/130 ` shows the PVlive value is 1.911 MW. Interesting, need to check if 1.88 needs updating

**Comment by peterdudfield** [comment]
I think there are two issues
1. `int` <-> float issue on production API
2. PVlive values > capacity values. 

1. Let me just check the versions and see if we have this problem on dev or not

2. 
```
from pvlive_api import PVLive
pvl = PVLive()
pvl.latest(entity_type="gsp", entity_id=130,extra_fields='installedcapacity_mwp')
(130, '2023-06-20T11:00:00Z', 1.91197, 1.883053)
```
Ill make a bug on Sheffield Solar github for this

**Comment by peterdudfield** [comment]
![Screenshot 2023-06-20 at 12 40 43](https://github.com/openclimatefix/nowcasting/assets/34686298/2a4f439f-519e-47af-ac48-da6a96a88e6e)
This fits that the capacity is an int, but it hsuold be a float. This makes sense that this bug only shows up in Scotland, as the rounding error is more signifcant

**Comment by dantravers** [comment]
Yeah makes sense.  I would have thought it might crop up in some of the small urban GSP, but it doesn't appear to.  (at least right now)

**Comment by peterdudfield** [comment]
This should be solved by upgrading the datamodel in the api - https://github.com/openclimatefix/uk-pv-national-gsp-api/pull/224

**Comment by peterdudfield** [comment]
Ill upgrade production now

**Comment by dantravers** [comment]
Thanks - that looks much more sensible!
