### ISSUE TITLE
probabilistic data visualization color options

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/nowcasting#374]
## Detailed Description
We're moving forward with the national probabilistic forecast data visualization

## Context
Would be good to see a couple UI options for the national probabilistic visualization. 

## Possible Implementation
Try some colors from the the color palette and provide some screenshots in a PR. 

1. `Hex: #E4E4E4 Opacity: 0.5`

![Screenshot 2023-07-10 at 13 36 53](https://github.com/openclimatefix/nowcasting/assets/86949265/6a0c64c6-2ed1-41b9-9b40-3475bc4e3908)

2. `Hex: #FFFDF6 Opacity:0.5`

![Screenshot 2023-07-10 at 14 08 54](https://github.com/openclimatefix/nowcasting/assets/86949265/b0d64fff-0f99-4737-8a0c-fcb9fb8950fd)

 3. `Hex:#FFD053 Opacity: 0.3`
![Screenshot 2023-07-10 at 13 40 02](https://github.com/openclimatefix/nowcasting/assets/86949265/c5568c3c-a555-43ae-b480-1a1134c10ac5)

4. `Hex: #FFAC5F Opacity:0.4 `
![Screenshot 2023-07-10 at 13 43 24](https://github.com/openclimatefix/nowcasting/assets/86949265/37af9a6b-5cbf-4282-b7e7-8c6f4c00886a)

5. `Hex: #7BCDF3 Opacity: 0.4`
![Screenshot 2023-07-10 at 13 46 47](https://github.com/openclimatefix/nowcasting/assets/86949265/c907bd6b-0acf-4ecf-bba2-db8dd0ff88b1)

6. `Hex: #63BCAF Opacity: 0.7`
![Screenshot 2023-07-10 at 13 49 46](https://github.com/openclimatefix/nowcasting/assets/86949265/25c6cb1d-8f86-4db7-8de9-e1c07157617c)

7. `Hex:  #7BCDF Opacity: 0.4`
![Screenshot 2023-07-10 at 13 54 03](https://github.com/openclimatefix/nowcasting/assets/86949265/5c529993-1663-4df9-98e2-317fb9786dde)

8. `Hex: #9EC8FA Opacity: 0.6`
![Screenshot 2023-07-10 at 13 59 53](https://github.com/openclimatefix/nowcasting/assets/86949265/7dca3165-7812-4a57-b100-2c6a66deba8d)

**Comment by peterdudfield** [comment]
I quick like 3.

**Comment by dantravers** [comment]
Yep, agree.  @braddf ?

**Comment by braddf** [comment]
@rachel-labri-tipton I like 3 as well! I think should be okay with the 4-hour, and we can re-assess after a bit if it is irksome in the wild. Opacity looks like a good start for sure as well 👍
