### ISSUE TITLE
New app layout with footer

### ISSUE THREAD

**Issue by dctanner** [openclimatefix/nowcasting#38]
New design app layout:

![image](https://user-images.githubusercontent.com/227/168634409-2d2115d8-a1c7-4e5e-9c80-e7dc1c73ba28.png)

Logos for footer (use svgs): https://drive.google.com/drive/folders/1nQ81oZsYM3_Hw0Pf4B4_Aycz7AJNUVeR

**Comment by dlinah** [comment]
@dctanner  @peterdudfield  will we be removing the old footer? (it contains some more details)
<img width="1440" alt="Screenshot 2022-05-16 at 14 00 09" src="https://user-images.githubusercontent.com/24292074/168589038-05ff4188-9688-461c-930e-059f9eda7149.png">

and the old navbar maybe needs a design update and should be visible all the time?

<img width="1438" alt="Screenshot 2022-05-16 at 13 59 57" src="https://user-images.githubusercontent.com/24292074/168588985-549b5d82-efcd-4c6b-981c-41db37359d12.png">

**Comment by dctanner** [comment]
Maybe we should remove the old footer, and add the profile dropdown to the new footer?

**Comment by peterdudfield** [comment]
See https://github.com/openclimatefix/nowcasting/issues/26 for more details on line plots and labels

**Comment by dlinah** [comment]
@JackKelly thanks for the update!

**Comment by dctanner** [comment]
@peterdudfield here is the current header+footer design. We need to remove the header or footer. Assuming we remove the header, do you have any views on where the round account icon should go?

![](https://user-images.githubusercontent.com/24292074/168606166-15bf61bf-8146-4a0e-a293-162428183ca6.png)
