### ISSUE TITLE
Upgrade apps to use quartz API routes

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#385]
## Detailed Description
Update the app to use new quartz routes

## Context
- Upgrading web app API routes from `nowcasting.io` to `quartz.solar` routes
- NG-ESO could not access new quarts routes, so might have to wait until that is solved - @peterdudfield has checked in with them and waiting to hear back

## Possible Implementation
- Change ENVs on respective branches in vercel
  - Quartz UI
    - Production
    - Staging
    - Previews
  - Sites UI / Quartz Mobile
    - Production
    - Staging
    - Previews

## Additional Information
This shouldn't affect Auth0 config AFAIK, as they are using the same `audience` etc. already 🤞

**Comment by peterdudfield** [comment]
SO this is main done apart from
- turn on forwarding if people use the old root - this casued a problem with NG_ESO last time
- update our apps? @braddf to clarify

**Comment by braddf** [comment]
Have amended the description re route updates, and the forwarding _should_ just work and redirect all users including NG-ESO – _if_ they can access the new route from the Control Room. 
It may be that the redirect is somehow upsetting a security policy or firewall or something, in which case the person signing in on the monitor just needs to be using the new `https://app.quartz.solar` URL

**Comment by peterdudfield** [comment]
This is done
