### ISSUE TITLE
Prevent UI from making requests too often

### ISSUE THREAD

**Issue by braddf** [openclimatefix/nowcasting#394]
## Describe the bug
It's possible (probably, in fact) that the UI is making more requests to the API than needed, and only taking notice of the latest request to return. This would cause unnecessary strain on the API, and if the cache isn't quite working properly, also the DB, which is more of an issue. This may or may not be the reason for the EC2 instance locking up and falling over periodically when multiple users are loading/actively using the UI simultaneously. 

## To Reproduce
1. Open the Quartz UI
2. Open browser DevTools > Network tab
3. Watch the requests being made by the UI as you click on charts/change view etc.
4. See many requests, and possibly then no requests returning successfully if the API falls over.

## Expected behavior
Should only be requesting new data periodically, perhaps at the 5 minute auto-update interval that the app runs internally, or at least not more than once every couple of minutes.

## Additional context
N/A

**Comment by peterdudfield** [comment]
this now done?
