### ISSUE TITLE
Nowcasting.io deployment

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#415]
## Detailed Description
Create new `nowcasting.io` deployment

## Context
- good to seperate `nowcasting.io` and `quartz.solar`
- need to move users over to `quartz.solar`

## Possible Implementation
- [x] Create new branch from `main` called `nowcasting.io`. make sure it is protected
- [x] make deployment on Vercel that looks at this branch
- [x] switch over on Vercel so that `app.nowcastiong.io` goes to this branch
- [x] Update `main` vercel env to look at `api.quartz.solar`

**Comment by braddf** [comment]
This should be all working now and looks good on the DB `api_request` table 👍
