### ISSUE TITLE
Hover over chart to see tooltip (1)

### ISSUE THREAD

**Issue by dctanner** [openclimatefix/nowcasting#42]
When you hover over the national or GSP chart, it should show a tooltip with the values at they point in time.

Use the existing Recharts tooltip feature, with a bit of styling of the tooltip: https://recharts.org/en-US/api/LineChart
The tooltip should work separately in both charts.

Ideally it should look similar to this, and include DD/MM as well as the time.

<img width="538" alt="CleanShot 2022-05-17 at 15 44 39@2x" src="https://user-images.githubusercontent.com/227/168839591-5f1576f0-374c-4b74-b573-3d8f21ebb447.png">

**Comment by peterdudfield** [comment]
For the hover, were we going to have 12:00 to 12:30, to show the time period its about

**Comment by dctanner** [comment]
> For the hover, were we going to have 12:00 to 12:30, to show the time period its about

Looking at how Recharts does the tooltip, I think it takes the x axis label from the chart. In the interest of speed, can I suggest we live without the range for now, and do that as a later enhancement?

**Comment by peterdudfield** [comment]
> > For the hover, were we going to have 12:00 to 12:30, to show the time period its about
> 
> Looking at how Recharts does the tooltip, I think it takes the x axis label from the chart. In the interest of speed, can I suggest we live without the range for now, and do that as a later enhancement?

yea, could we make an issue for it though, otherwise we'll forget
