### ISSUE TITLE
Show error alert notice when any API request fails (both map and chart) (2)

### ISSUE THREAD

**Issue by dctanner** [openclimatefix/nowcasting#43]
Implement general purpose error notice component. Multiple errors can be visible at the same time. They should stack on top of one another, from the top down, with some margin spacing between them.
X closes the error, if X is not clicked within 10 seconds it closes itself automatically.

Use this initially to show an error when any API request fails: "Error fetching data. Retrying now…"

Now that we can show useful error messages, we should also make the map failure state more elegant. When the api call to get the data for the map fails, it should show the new error message, but the map should still be visible (showing the data from the previous API call that succeeded).

![image](https://user-images.githubusercontent.com/227/168846871-353ba0bb-e916-4f03-9cdc-53e71e441e86.png)

**Comment by peterdudfield** [comment]
looks good

**Comment by dlinah** [comment]
@dctanner what do you mean by "we can show useful error messages" ?, do you mean we should show the error coming from the server?
