### ISSUE TITLE
Allow clicking on any point in the chart forecast to view the GSP forecast map at that time (2)

### ISSUE THREAD

**Issue by dctanner** [openclimatefix/nowcasting#45]
(for now we will only allow clicking on the forecast section of the graph and not the history, until #48 is done).

Clicking at any point of the forecast on the chart does the following:

- [x] Updates white now line and label to be at that point
- [x] Updates GW number next to National to be the value of the yellow line at that point
- [x] Updates map timestamp to be that point
- [x] Updates map GSP yellow fill-opacity to be the gsp data at that point

**Note:** if the GSP chart is visible, the national and GSP charts should be connected, it should always be updated to the same point. You can click on either chart, and it will update the point to be the same on both of them. 

Add a new button 'Reset Time' which resets the time in the chart (white dashed line) to be the current 30minNOW (which should update as new forecasts come in).

![Image](https://user-images.githubusercontent.com/227/169779228-bed0db25-7aa9-4444-8641-a6a4a5f86a8f.png)

**Comment by peterdudfield** [comment]
I discussed with Dan. We are happy with two buttons
- 'reset' button, that goes back to showing the the 'now' forecast
- play/pause button that start the animation and pauses it. 

I believe this fits with the current issue description.
