### ISSUE TITLE
Click GSP tweaks

### ISSUE THREAD

**Issue by dctanner** [openclimatefix/nowcasting#57]
1. GSP chart yellow solid line doesn't go back as far in time as National. The OCF Forecast data for a GSP chart needs to come from the API call which includes the history.
2. Round GSP % to whole number with no decimal places
3. It's hard to see the shape of GSP regions when they have no yellow colour. Let's add a 1px border around all GSP regions. It should be a faint white colour.

**Comment by peterdudfield** [comment]
Ive put some details for 3. in here - https://github.com/openclimatefix/nowcasting/issues/59

**Comment by peterdudfield** [comment]
Ive put some details for 1. in here - https://github.com/openclimatefix/nowcasting/issues/59

**Comment by peterdudfield** [comment]
1. can also be solved by https://github.com/openclimatefix/nowcasting/issues/48 which is nearly ready

**Comment by dlinah** [comment]
@dctanner, gsp outline in white 
![Screenshot 2022-06-01 at 13 12 31](https://user-images.githubusercontent.com/24292074/171391602-9451fc17-4439-463b-a2e6-8ee15fd695fb.png)
and if it's in yellow it interferes less with the white outline underneath 
![Screenshot 2022-06-01 at 13 11 59](https://user-images.githubusercontent.com/24292074/171392045-0a380fdf-caf4-4eaf-a821-4bda6b66c660.png)

**Comment by peterdudfield** [comment]
Should we reopen this as 1. is not done yet. Not #48 is neary done, just needs checking

**Comment by peterdudfield** [comment]
This looks done now
