### ISSUE TITLE
Update Colour Scheme of Nowcasting App

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/nowcasting#61]
The [updated colour scheme is available here](https://coolors.co/ffd053-ffac5f-e4e4e4-14120e-48b0df-63bcaf-70c2b6).

Additionally, the [relevant Tailwind config can be found in `apps/nowcasting-website/tailwind.config.json` in the `marketing-site` branch](https://github.com/openclimatefix/nowcasting/blob/29bd4727dcbdeddc927a0961161497e6a70a0352/apps/nowcasting-website/tailwind.config.js) (or maybe in `main` by now). 😊

**Comment by peterdudfield** [comment]
This be done @dlinah ?
