### ISSUE TITLE
fix ui bugs

### ISSUE THREAD

**Issue by dlinah** [openclimatefix/nowcasting#67]
fix ui bugs mentioned in #53
1. fixed in #62
>~~I just noticed the date format is incorrect for me (in the chart tooltip and map). It should be "DD/MM/YYYY HH:MM". Not like this:~~ 
<img alt="CleanShot 2022-05-29 at 16 59 06@2x" width="154" src="https://user-images.githubusercontent.com/227/170879142-9ee89f6b-3e50-4053-a504-0127ed0bc568.png"> <img alt="CleanShot 2022-05-29 at 16 59 25@2x" width="219" src="https://user-images.githubusercontent.com/227/170879169-0da0cc7a-dfa2-458e-b903-cc8561bbc9da.png">

3.

> If the browser height is too short, the layout breaks. We should instead make the left hand side of the page scroll (whilst keeping the map fixed full height (should also fix https://github.com/openclimatefix/nowcasting/issues/64 at the same time): ![CleanShot 2022-05-29 at 16 46 57@2x](https://user-images.githubusercontent.com/227/170878886-ee07f096-726f-4e4d-a63f-9c997caf4128.png)

**Comment by dctanner** [comment]
@dlinah fyi added link to https://github.com/openclimatefix/nowcasting/issues/64

**Comment by dctanner** [comment]
@dlinah fyi added link to https://github.com/openclimatefix/nowcasting/issues/64
