### ISSUE TITLE
Solid line up to now

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#69]
## Detailed Description

Currently, the solid line goes up to the time selected and the dashed yellow line after this. 

Would be great if the solid line goes up to 'now' and the dashed line further from this.

<img width="636" alt="Screenshot 2022-06-08 at 08 21 50" src="https://user-images.githubusercontent.com/34686298/172556508-999f50d7-372a-4f0a-bffa-1bf51ed3355a.png">
Note the screen shot was taken around 07.30 UTC

## Context
This clearly shows what is in the past

## Possible Implementation
...

**Comment by dantravers** [comment]
Yes, this only happens when you click at different times on the line chart, but is confusing, as the "future" should be dotted and the only dotted line.  The clicking at different times just changes the heatmap on the right.

**Comment by peterdudfield** [comment]
> Yes, this only happens when you click at different times on the line chart, but is confusing, as the "future" should be dotted and the only dotted line. The clicking at different times just changes the heatmap on the right.

And clicking would update where the dashed white line and marker is.
