### ISSUE TITLE
Info text

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#76]
Add a 'i' icon below GSP chart (bottom left of screen)
see examples [here](https://www.google.com/search?q=info+icon&tbm=isch&ved=2ahUKEwj9udWc0bv4AhXCYfEDHfcaAWAQ2-cCegQIABAA&oq=info+icon&gs_lcp=CgNpbWcQAzIECAAQQzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDoHCAAQsQMQQzoICAAQgAQQsQM6CwgAEIAEELEDEIMBUKIIWPMQYKUSaABwAHgAgAFNiAHHBZIBAjEwmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=1DKwYv3_B8LDxc8P97WEgAY&bih=1118&biw=2280&rlz=1C5CHFA_enGB966GB966)

Add info button with hover / tool tip:
- All datetimes are in Europe/London.
- Following PVLive ([link](https://www.solar.sheffield.ac.uk/pvlive/)), datetimes show the end of the Settlement period. I.e 17:00 refers to solar generation between 16:30 to 17:00. 
- Charts units are in MW

**Comment by JackKelly** [comment]
I strongly believe that the timezone should be *very* clearly shown (i.e. don't "hide" it in a "question mark")! Especially if the timezone is UTC. Users will almost certainly expect the TZ to be Europe/London (i.e. UTC+1 right now), and so it'll be surprising to them that the graph is showing times in UTC.

TBH, my preference would be to show the times in Europe/London, and say the timezone is "BST" on the plots; and then worry about how to display graphs when part of the graph if UTC and part UTC+1 when we get to the next daylight saving transition later this year :slightly_smiling_face:

**Comment by peterdudfield** [comment]
All times are now changed to Europe London. 

perhaps now under the question is enough to say 
'All times are now changed to Europe London. '

**Comment by peterdudfield** [comment]
Ready for @Alaatohamy and or @dlinah

**Comment by peterdudfield** [comment]
I have a little go at this, but @dlinah feel free to do it the best way
https://github.com/openclimatefix/nowcasting/commit/8a365250943513884c9b31c16e1320ca0db1cfb0

**Comment by dlinah** [comment]
@peterdudfield thanks! , i created another branch for it, used your code but removed the MUI library because we are already using tailwind
