### ISSUE TITLE
Make graph popup semi-translucent

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting#81]
The popup which appears on mouseover of the line graph often obscures the others parts of the line graph you want to see.

In the short term, can we experiment with making the popup semi-translucent.  We don't know what this will look like, so please try it out once or twice and send screenshot to Peter and Dan and we can give a view.

**Comment by dlinah** [comment]
here a preview with a transparent  background 


![Image](https://user-images.githubusercontent.com/24292074/174503348-d79b6013-7c57-4f31-ae89-983be0f3f112.png)

**Comment by peterdudfield** [comment]
Above is 60%

could we try 80%?

**Comment by dantravers** [comment]
Agree - 80 looks good

**Comment by dlinah** [comment]
@peterdudfield yes already is just gonna add the pr
